// Conteúdo padrão do app. Tudo em português, pensado para ser lido em voz alta.
// Cada item tem: id, rótulo curto (mostrado no cartão), texto falado (o que o TTS diz),
// emoji (ícone grande) e cor de fundo do cartão.

export const CATEGORIES = [
  {
    id: "preciso",
    label: "Preciso",
    emoji: "🆘",
    color: "#ff8a65",
    cards: [
      { id: "agua", label: "Água", speak: "Água", emoji: "💧" },
      { id: "fome", label: "Fome", speak: "Estou com fome", emoji: "🍴" },
      { id: "sede", label: "Sede", speak: "Estou com sede", emoji: "🥤" },
      { id: "banheiro", label: "Banheiro", speak: "Banheiro", emoji: "🚽" },
      { id: "dor", label: "Dor", speak: "Estou com dor", emoji: "🤕" },
      { id: "cansado", label: "Cansado", speak: "Estou cansado", emoji: "😴" },
      { id: "frio", label: "Frio", speak: "Estou com frio", emoji: "🥶" },
      { id: "calor", label: "Calor", speak: "Estou com calor", emoji: "🥵" },
      { id: "dormir", label: "Dormir", speak: "Quero dormir", emoji: "🛌" },
      { id: "descansar", label: "Descansar", speak: "Quero descansar", emoji: "🛋️" },
      { id: "remedio", label: "Remédio", speak: "Preciso de remédio", emoji: "💊" },
      { id: "banho", label: "Tomar banho", speak: "Quero tomar banho", emoji: "🚿" },
      { id: "escovar", label: "Escovar dente", speak: "Quero escovar o dente", emoji: "🪥" },
      { id: "trocar_roupa", label: "Trocar roupa", speak: "Quero trocar de roupa", emoji: "👕" },
      { id: "ajuda", label: "Ajuda", speak: "Preciso de ajuda", emoji: "🆘" },
    ],
  },
  {
    id: "corpo",
    label: "Dói aqui",
    emoji: "🤕",
    color: "#ef5350",
    cards: [
      { id: "dor_cabeca", label: "Cabeça", speak: "Está doendo a cabeça", emoji: "🤕" },
      { id: "dor_barriga", label: "Barriga", speak: "Está doendo a barriga", emoji: "🤢" },
      { id: "dor_dente", label: "Dente", speak: "Está doendo o dente", emoji: "🦷" },
      { id: "dor_garganta", label: "Garganta", speak: "Está doendo a garganta", emoji: "😷" },
      { id: "dor_ouvido", label: "Ouvido", speak: "Está doendo o ouvido", emoji: "👂" },
      { id: "dor_olho", label: "Olho", speak: "Está doendo o olho", emoji: "👁️" },
      { id: "dor_braco", label: "Braço", speak: "Está doendo o braço", emoji: "💪" },
      { id: "dor_mao", label: "Mão", speak: "Está doendo a mão", emoji: "✋" },
      { id: "dor_perna", label: "Perna", speak: "Está doendo a perna", emoji: "🦵" },
      { id: "dor_pe", label: "Pé", speak: "Está doendo o pé", emoji: "🦶" },
      { id: "dor_costas", label: "Costas", speak: "Está doendo as costas", emoji: "🩹" },
    ],
  },
  {
    id: "sentimentos",
    label: "Sentimentos",
    emoji: "😊",
    color: "#ffca28",
    cards: [
      { id: "feliz", label: "Feliz", speak: "Estou feliz", emoji: "😃" },
      { id: "triste", label: "Triste", speak: "Estou triste", emoji: "😢" },
      { id: "bravo", label: "Bravo", speak: "Estou bravo", emoji: "😠" },
      { id: "medo", label: "Com medo", speak: "Estou com medo", emoji: "😨" },
      { id: "calmo", label: "Calmo", speak: "Estou calmo", emoji: "😌" },
      { id: "surpreso", label: "Surpreso", speak: "Estou surpreso", emoji: "😮" },
      { id: "animado", label: "Animado", speak: "Estou animado", emoji: "🤩" },
      { id: "envergonhado", label: "Envergonhado", speak: "Estou envergonhado", emoji: "😳" },
      { id: "entediado", label: "Entediado", speak: "Estou entediado", emoji: "🥱" },
      { id: "confuso", label: "Confuso", speak: "Estou confuso", emoji: "😕" },
      { id: "saudade", label: "Com saudade", speak: "Estou com saudade", emoji: "🥺" },
      { id: "orgulhoso", label: "Orgulhoso", speak: "Estou orgulhoso", emoji: "😎" },
    ],
  },
  {
    id: "quero",
    label: "Quero",
    emoji: "🙋",
    color: "#66bb6a",
    cards: [
      { id: "sim", label: "Sim", speak: "Sim", emoji: "✅" },
      { id: "nao", label: "Não", speak: "Não", emoji: "❌" },
      { id: "quero", label: "Quero", speak: "Eu quero", emoji: "🙋" },
      { id: "nao_quero", label: "Não quero", speak: "Eu não quero", emoji: "🙅" },
      { id: "mais", label: "Mais", speak: "Quero mais", emoji: "➕" },
      { id: "chega", label: "Chega", speak: "Chega", emoji: "✋" },
      { id: "vamos", label: "Vamos", speak: "Vamos", emoji: "🚶" },
      { id: "espera", label: "Espera", speak: "Espera um pouco", emoji: "⏳" },
      { id: "de_novo", label: "De novo", speak: "De novo", emoji: "🔁" },
      { id: "terminei", label: "Terminei", speak: "Terminei", emoji: "🏁" },
      { id: "nao_sei", label: "Não sei", speak: "Eu não sei", emoji: "🤷" },
      { id: "obrigado", label: "Obrigado", speak: "Obrigado", emoji: "🙏" },
      { id: "por_favor", label: "Por favor", speak: "Por favor", emoji: "🙏" },
      { id: "desculpa", label: "Desculpa", speak: "Desculpa", emoji: "😔" },
    ],
  },
  {
    id: "acoes",
    label: "Ações",
    emoji: "🎯",
    color: "#29b6f6",
    cards: [
      { id: "brincar", label: "Brincar", speak: "Quero brincar", emoji: "🧸" },
      { id: "tv", label: "Assistir TV", speak: "Quero assistir TV", emoji: "📺" },
      { id: "musica", label: "Ouvir música", speak: "Quero ouvir música", emoji: "🎵" },
      { id: "passear", label: "Passear", speak: "Quero passear", emoji: "🚶" },
      { id: "desenhar", label: "Desenhar", speak: "Quero desenhar", emoji: "🎨" },
      { id: "ler", label: "Ler", speak: "Quero ler", emoji: "📖" },
      { id: "bola", label: "Jogar bola", speak: "Quero jogar bola", emoji: "⚽" },
      { id: "dancar", label: "Dançar", speak: "Quero dançar", emoji: "💃" },
      { id: "celular", label: "Celular", speak: "Quero usar o celular", emoji: "📱" },
      { id: "videogame", label: "Videogame", speak: "Quero jogar videogame", emoji: "🎮" },
    ],
  },
  {
    id: "comida",
    label: "Comida",
    emoji: "🍎",
    color: "#8d6e63",
    cards: [
      { id: "agua2", label: "Água", speak: "Água", emoji: "💧" },
      { id: "suco", label: "Suco", speak: "Suco", emoji: "🧃" },
      { id: "leite", label: "Leite", speak: "Leite", emoji: "🥛" },
      { id: "pao", label: "Pão", speak: "Pão", emoji: "🍞" },
      { id: "arroz", label: "Arroz", speak: "Arroz", emoji: "🍚" },
      { id: "feijao", label: "Feijão", speak: "Feijão", emoji: "🫘" },
      { id: "fruta", label: "Fruta", speak: "Fruta", emoji: "🍌" },
      { id: "biscoito", label: "Biscoito", speak: "Biscoito", emoji: "🍪" },
      { id: "macarrao", label: "Macarrão", speak: "Macarrão", emoji: "🍝" },
      { id: "pizza", label: "Pizza", speak: "Pizza", emoji: "🍕" },
      { id: "chocolate", label: "Chocolate", speak: "Chocolate", emoji: "🍫" },
      { id: "sorvete", label: "Sorvete", speak: "Sorvete", emoji: "🍦" },
    ],
  },
  {
    id: "pessoas",
    label: "Pessoas",
    emoji: "👪",
    color: "#5c6bc0",
    cards: [
      { id: "mamae", label: "Mamãe", speak: "Mamãe", emoji: "👩" },
      { id: "papai", label: "Papai", speak: "Papai", emoji: "👨" },
      { id: "irmao", label: "Irmão", speak: "Irmão", emoji: "🧑" },
      { id: "amigo", label: "Amigo", speak: "Amigo", emoji: "🤝" },
      { id: "vovo", label: "Vovó", speak: "Vovó", emoji: "👵" },
      { id: "vovo_m", label: "Vovô", speak: "Vovô", emoji: "👴" },
      { id: "tio", label: "Tio", speak: "Tio", emoji: "👨‍🦱" },
      { id: "tia", label: "Tia", speak: "Tia", emoji: "👩‍🦱" },
      { id: "professor", label: "Professor", speak: "Professor", emoji: "👨‍🏫" },
      { id: "medico", label: "Médico", speak: "Médico", emoji: "🧑‍⚕️" },
    ],
  },
  {
    id: "lugares",
    label: "Lugares",
    emoji: "🏠",
    color: "#ab47bc",
    cards: [
      { id: "casa", label: "Casa", speak: "Casa", emoji: "🏠" },
      { id: "quarto", label: "Quarto", speak: "Quarto", emoji: "🛏️" },
      { id: "cozinha", label: "Cozinha", speak: "Cozinha", emoji: "🍳" },
      { id: "escola", label: "Escola", speak: "Escola", emoji: "🏫" },
      { id: "rua", label: "Rua", speak: "Rua", emoji: "🛣️" },
      { id: "carro", label: "Carro", speak: "Carro", emoji: "🚗" },
      { id: "parque", label: "Parque", speak: "Parque", emoji: "🌳" },
      { id: "praia", label: "Praia", speak: "Praia", emoji: "🏖️" },
      { id: "loja", label: "Loja", speak: "Loja", emoji: "🏬" },
      { id: "hospital", label: "Hospital", speak: "Hospital", emoji: "🏥" },
    ],
  },
];

// Atividades padrão do "Aprender". Cada uma tem um "display" que diz como os itens
// aparecem e se comportam ao tocar: "color" (retângulo colorido), "letter" (letra grande
// + palavra ilustrada) ou "number" (número grande + pontinhos). Itens customizados
// adicionados pela família (dentro de qualquer atividade) sempre usam o estilo simples
// de cartão com emoji, independente do "display" da atividade.
export const LEARN_ACTIVITIES = [
  {
    id: "cores",
    label: "Cores",
    emoji: "🎨",
    color: "#ec407a",
    cssClass: "learn-card--cores",
    display: "color",
    items: [
      { id: "vermelho", label: "Vermelho", hex: "#e53935", text: "#ffffff" },
      { id: "azul", label: "Azul", hex: "#1e88e5", text: "#ffffff" },
      { id: "amarelo", label: "Amarelo", hex: "#fdd835", text: "#5a4600" },
      { id: "verde", label: "Verde", hex: "#43a047", text: "#ffffff" },
      { id: "laranja", label: "Laranja", hex: "#fb8c00", text: "#ffffff" },
      { id: "roxo", label: "Roxo", hex: "#8e24aa", text: "#ffffff" },
      { id: "rosa", label: "Rosa", hex: "#ec407a", text: "#ffffff" },
      { id: "marrom", label: "Marrom", hex: "#6d4c41", text: "#ffffff" },
      { id: "preto", label: "Preto", hex: "#212121", text: "#ffffff" },
      { id: "branco", label: "Branco", hex: "#fafafa", text: "#333333" },
      { id: "cinza", label: "Cinza", hex: "#9e9e9e", text: "#ffffff" },
    ],
  },
  {
    id: "letras",
    label: "Letras",
    emoji: "🔤",
    color: "#7e57c2",
    cssClass: "learn-card--letras",
    display: "letter",
    items: [
      { id: "A", label: "A", word: "Abelha", emoji: "🐝" },
      { id: "B", label: "B", word: "Bola", emoji: "⚽" },
      { id: "C", label: "C", word: "Cachorro", emoji: "🐶" },
      { id: "D", label: "D", word: "Dado", emoji: "🎲" },
      { id: "E", label: "E", word: "Elefante", emoji: "🐘" },
      { id: "F", label: "F", word: "Foguete", emoji: "🚀" },
      { id: "G", label: "G", word: "Gato", emoji: "🐱" },
      { id: "H", label: "H", word: "Hipopótamo", emoji: "🦛" },
      { id: "I", label: "I", word: "Igreja", emoji: "⛪" },
      { id: "J", label: "J", word: "Jacaré", emoji: "🐊" },
      { id: "K", label: "K", word: "Kiwi", emoji: "🥝" },
      { id: "L", label: "L", word: "Leão", emoji: "🦁" },
      { id: "M", label: "M", word: "Macaco", emoji: "🐵" },
      { id: "N", label: "N", word: "Navio", emoji: "🚢" },
      { id: "O", label: "O", word: "Ovo", emoji: "🥚" },
      { id: "P", label: "P", word: "Pato", emoji: "🦆" },
      { id: "Q", label: "Q", word: "Queijo", emoji: "🧀" },
      { id: "R", label: "R", word: "Rato", emoji: "🐭" },
      { id: "S", label: "S", word: "Sol", emoji: "☀️" },
      { id: "T", label: "T", word: "Tartaruga", emoji: "🐢" },
      { id: "U", label: "U", word: "Uva", emoji: "🍇" },
      { id: "V", label: "V", word: "Vaca", emoji: "🐮" },
      { id: "W", label: "W", word: "Wi-Fi", emoji: "📶" },
      { id: "X", label: "X", word: "Xadrez", emoji: "♟️" },
      { id: "Y", label: "Y", word: "Yoga", emoji: "🧘" },
      { id: "Z", label: "Z", word: "Zebra", emoji: "🦓" },
    ],
  },
  {
    id: "numeros",
    label: "Números",
    emoji: "🔢",
    color: "#fb8c00",
    cssClass: "learn-card--numeros",
    display: "number",
    items: Array.from({ length: 11 }, (_, n) => ({
      id: String(n),
      label: String(n),
      dots: "⚫".repeat(n),
    })),
  },
];

// Grupos de emoji para o seletor visual (usado ao criar palavras e categorias).
// O grupo "Pessoas" vem primeiro e com bastante variedade, para facilitar achar
// um emoji parecido com a pessoa que está sendo cadastrada.
export const EMOJI_GROUPS = [
  {
    id: "pessoas",
    label: "Pessoas",
    icon: "🧑",
    emojis: [
      "👶", "🧒", "👦", "👧", "🧑", "👨", "👩", "🧑‍🦱", "👨‍🦱", "👩‍🦱",
      "🧑‍🦰", "👨‍🦰", "👩‍🦰", "🧑‍🦳", "👨‍🦳", "👩‍🦳", "🧑‍🦲", "👨‍🦲", "👩‍🦲", "👴",
      "👵", "🧓", "👱", "👱‍♂️", "👱‍♀️", "🧔", "🧔‍♂️", "🧔‍♀️", "🤱", "🤰",
      "👨‍⚕️", "👩‍⚕️", "👨‍🏫", "👩‍🏫", "👮‍♂️", "👮‍♀️", "👨‍🍳", "👩‍🍳", "🕵️‍♂️", "🕵️‍♀️",
      "👨‍🔧", "👩‍🔧", "🤴", "👸", "🧑‍🦯", "🧑‍🦼", "🧑‍🦽",
    ],
  },
  {
    id: "rostos",
    label: "Rostos",
    icon: "😊",
    emojis: [
      "😀", "😃", "😄", "😁", "😊", "🙂", "😉", "😍", "🥰", "😘",
      "🤗", "🤩", "😎", "😏", "😒", "😞", "😔", "🙁", "😣", "😖",
      "😫", "😢", "😭", "😤", "😠", "😡", "🤬", "😨", "😰", "😥",
      "🥵", "🥶", "😴", "🤒", "🤕", "🤢", "🤧", "😷", "🥱", "🤔",
      "😮", "😯", "😲", "😱", "🥺", "😳",
    ],
  },
  {
    id: "comida",
    label: "Comida",
    icon: "🍎",
    emojis: [
      "🍎", "🍌", "🍇", "🍓", "🍉", "🍊", "🍍", "🥭", "🍑", "🍒",
      "🍅", "🥕", "🌽", "🥦", "🍞", "🧀", "🍗", "🍔", "🍕", "🌭",
      "🍟", "🥪", "🌮", "🍝", "🍜", "🍲", "🍣", "🍩", "🍪", "🎂",
      "🍫", "🍬", "🍭", "🍦", "🍨", "🥛", "☕", "🧃", "🥤",
    ],
  },
  {
    id: "lugares",
    label: "Lugares",
    icon: "🏠",
    emojis: [
      "🏠", "🏡", "🏫", "🏥", "🏬", "🏪", "🏦", "🏨", "🏰", "⛪",
      "🏟️", "🌳", "🏖️", "🏞️", "🏙️", "🚗", "🚌", "🚲", "🚂", "✈️",
      "⛵",
    ],
  },
  {
    id: "atividades",
    label: "Atividades",
    icon: "⚽",
    emojis: [
      "⚽", "🏀", "🏈", "⚾", "🎾", "🏐", "🎱", "🏓", "🏸", "🥊",
      "🎮", "🎲", "🧩", "🎨", "🎭", "🎬", "🎤", "🎧", "🎸", "🥁",
      "🎹", "📚", "📖", "✏️", "🖍️", "🧸", "🪁", "🎯", "🚴", "🏊",
    ],
  },
  {
    id: "animais",
    label: "Animais",
    icon: "🐶",
    emojis: [
      "🐶", "🐱", "🐭", "🐹", "🐰", "🦊", "🐻", "🐼", "🐨", "🐯",
      "🦁", "🐮", "🐷", "🐸", "🐵", "🐔", "🐧", "🐦", "🐤", "🦆",
      "🦉", "🐺", "🐴", "🦄", "🐝", "🦋", "🐢", "🐍", "🐙", "🐬",
      "🐳", "🐘", "🦒", "🦓",
    ],
  },
  {
    id: "natureza",
    label: "Natureza",
    icon: "🌈",
    emojis: [
      "🌞", "🌙", "⭐", "🌈", "☀️", "⛅", "🌧️", "❄️", "🔥", "💧",
      "🌸", "🌼", "🌻", "🌺", "🍀", "🌵", "🎈", "🎁", "❤️", "💙",
      "💚", "💛", "🧡", "💜", "🖤", "🤍", "🤎", "✨",
    ],
  },
];
